### ISSUE TITLE
Missing Meeting Notes

### ISSUE THREAD

**Issue by fandywie** [greenido/lpa-1#75] opened 2016-06-15 15:31 UTC
I am unable to find Notes that I entered Yesterday.

![screen shot 2016-06-15 at 8 28 09 am](https://cloud.githubusercontent.com/assets/2950013/16086074/23fbe35a-32d3-11e6-874a-cd44aa06e254.png)

**Comment by greenido** [comment] 2016-06-15 19:46
Can you please try to refresh the app?

**Comment by fandywie** [comment] 2016-06-15 19:52
No luck, it's not showing up.

**Comment by greenido** [comment] 2016-06-16 08:20
I see your notes in our DB. 

Can you please try and open the app in a incognito window?
Sorry for the trouble.

**Comment by fandywie** [comment] 2016-06-16 16:05
No luck, the data I entered on the 15th (Yesterday) is there, but not the one on the 14th

**Comment by greenido** [comment] 2016-06-16 16:12
:( I'll keep investigate it.
Thanks!

**Comment by greenido** [comment] 2016-06-26 06:58
Closing as I can't reproduce it anymore. If it does popup in the future - please open it.
Thanks.

**Closed as completed by greenido** 2016-06-26 06:58 UTC
